---
title: "test"
author: "William Nicholas"
date: "September 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(dplyr)
library(tools)
library(stringr)
library(zoo)
library(reshape2)

# Read in lake level data from GLERL site
clair <- read.csv('clair1918.csv')
#read.csv('https://www.glerl.noaa.gov/data/dashboard/data/levels/1918_PRES/clair1918.csv', skip=2)
clair$Lake <- 'Lake St. Clair'
miHuron  <- read.csv('miHuron1918.csv')
#read.csv('https://www.glerl.noaa.gov/data/dashboard/data/levels/1918_PRES/miHuron1918.csv', skip=2)
miHuron$Lake <- 'Lake Michigan-Huron'
erie  <- read.csv('erie1918.csv')
#read.csv('https://www.glerl.noaa.gov/data/dashboard/data/levels/1918_PRES/erie1918.csv', skip=2)
erie$Lake <- 'Lake Erie'
superior <- read.csv('superior1918.csv')
#read.csv('https://www.glerl.noaa.gov/data/dashboard/data/levels/1918_PRES/superior1918.csv', skip=2)
superior$Lake <- 'Lake Superior'
ontario  <- read.csv('ontario1918.csv')
#read.csv('https://www.glerl.noaa.gov/data/dashboard/data/levels/1918_PRES/ontario1918.csv', skip=2)
ontario$Lake <- 'Lake Ontario'

lakes <- data.frame(bind_rows(clair, miHuron, erie, superior, ontario))
lakes <- melt(data = lakes, id.vars = c("year", 'Lake'), measure.vars = c('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'))
lakes$variable <- str_to_title(lakes$variable)
lakes$variable <- match(lakes$variable,month.abb)
lakes$Date <- as.yearmon(paste(lakes$year, lakes$variable, '1'), "%Y %m %d")
lakes <- lakes[-c(1, 3)]
lakes2 <- select(filter(lakes, Lake %in% input$lake_drop), c(Lake, Date, value))
lakes2 <- select(filter(lakes2, Date >= min(input$dates)), c(Lake, Date, value))
lakes2 <- select(filter(lakes2, Date <= max(input$dates)), c(Lake, Date, value))
lakes2

```